### ISSUE TITLE
"Tracks are already synchronized"

### ISSUE THREAD

**Issue by send0r** [StephenCasella/SoundCloud-Playlist-Sync#13]
When I try to download something I get this message, but no files are in the directory/downloaded except an empty manifest file.

**Comment by erwinkramer** [comment]
Hi @send0r ,

Please try the updated version of the application at my profile, if the issue still persists then please post an issue at my project page.

**Comment by StephenCasella** [comment]
@erwinkramer, thanks for taking this app beyond where I left it. As probably goes without saying I long ago lost the time to maintain this project. I have given you push access to this repository; feel free to update the readme to refer to your fork since that is where users will find the most value.

**Comment by send0r** [comment]
Hi @erwinkramer,
I get this error even with your version. Unfortunately, I'm not able to cerate an issue on your project page.

**Comment by mpratt14** [comment]
Hey there @StephenCasella, its good to finally see something from you lol. I remember about a year ago being very frustrated that your latest release stopped working, but then @erwinkramer showed up out of nowhere and just fixed everything with his code magics. I have been in good communication with him and have been suggesting/testing the features of his versions throughout his pull's history. Might as well take this time to thank you both, as having this app has allowed me to have my soundcloud collection locally in the easiest way possible. It certainly would take me the rest of my life if I did this manually (I have about 11000 tracks :100: X :100: :+1: :fire:).

**Comment by mpratt14** [comment]
@send0r So...

Just to verify, you are using this right?
https://github.com/erwinkramer/SoundCloud-Playlist-Sync/releases/download/r2.10.1.7/Soundcloud.Playlist.Sync_2_10_1_7.zip

What are you trying to do with it? Downloading your likes or just a playlist? Can you maybe post a screenshot of your settings right before you hit synchronize?
Do you have Antivirus, and did it give you any warnings when you launched it?

I can only imagine that this error would happen because you are downloading a playlist with a set of tracks that are all private...but im not sure

**Comment by send0r** [comment]
Yes, I used this one. However I just reinstalled everything and for some reasons my AntiVirus deleted NAudio.dll... Just restored it and it's working fine now.
Thanks for trying to help and sorry for kind of wasting your time
